<?php 
	// COLORES
	$disponible = "#73d287";
	$ocupado = "#968F8D";


	$planos1 = [
		[
			'idx' 		=> '0',
			'lugar' 	=> '12',
			'empresa' 	=> 'Empresa 1',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '1',
			'lugar' 	=> '13',
			'empresa' 	=> 'Empresa 2',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '2',
			'lugar' 	=> '14',
			'empresa' 	=> 'Empresa 3',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '3',
			'lugar' 	=> '15',
			'empresa' 	=> 'Empresa 4',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '4',
			'lugar' 	=> '16',
			'empresa' 	=> 'Empresa 5',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '5',
			'lugar' 	=> '17',
			'empresa' 	=> 'Empresa 6',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '6',
			'lugar' 	=> '18',
			'empresa' 	=> 'Empresa 7',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '7',
			'lugar' 	=> '19',
			'empresa' 	=> 'Empresa 8',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '8',
			'lugar' 	=> '20',
			'empresa' 	=> 'Empresa 9',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '9',
			'lugar' 	=> '21',
			'empresa' 	=> 'Empresa 10',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '10',
			'lugar' 	=> '22',
			'empresa' 	=> 'Empresa 11',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '11',
			'lugar' 	=> '23',
			'empresa' 	=> 'Empresa 12',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '12',
			'lugar' 	=> '24',
			'empresa' 	=> 'Empresa 13',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '13',
			'lugar' 	=> '25',
			'empresa' 	=> 'Empresa 14',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '14',
			'lugar' 	=> '26',
			'empresa' 	=> 'Empresa 15',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '15',
			'lugar' 	=> '27',
			'empresa' 	=> 'Empresa 16',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '16',
			'lugar' 	=> '28',
			'empresa' 	=> 'Empresa 17',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '17',
			'lugar' 	=> '29',
			'empresa' 	=> 'Empresa 18',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '18',
			'lugar' 	=> '30',
			'empresa' 	=> 'Empresa 19',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '19',
			'lugar' 	=> '31',
			'empresa' 	=> 'Empresa 20',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '20',
			'lugar' 	=> '32',
			'empresa' 	=> 'Empresa 21',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '21',
			'lugar' 	=> '33',
			'empresa' 	=> 'Empresa 22',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '22',
			'lugar' 	=> '34',
			'empresa' 	=> 'Empresa 23',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '23',
			'lugar' 	=> '35',
			'empresa' 	=> 'Empresa 24',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '24',
			'lugar' 	=> '36',
			'empresa' 	=> 'Empresa 25',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '25',
			'lugar' 	=> '37',
			'empresa' 	=> 'Empresa 26',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '26',
			'lugar' 	=> '38',
			'empresa' 	=> 'Empresa 27',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '27',
			'lugar' 	=> '39',
			'empresa' 	=> 'Empresa 28',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '28',
			'lugar' 	=> '40',
			'empresa' 	=> 'Empresa 29',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '29',
			'lugar' 	=> '41',
			'empresa' 	=> 'Empresa 30',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '30',
			'lugar' 	=> '42',
			'empresa' 	=> 'Empresa 31',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '31',
			'lugar' 	=> '43',
			'empresa' 	=> 'Empresa 32',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '32',
			'lugar' 	=> '44',
			'empresa' 	=> 'Empresa 33',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '33',
			'lugar' 	=> '45',
			'empresa' 	=> 'Empresa 34',
			'estatus' 	=> $disponible,
		],

		[
			'idx' 		=> '34',
			'lugar' 	=> '46',
			'empresa' 	=> 'Empresa 35',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '35',
			'lugar' 	=> '47',
			'empresa' 	=> 'Empresa 36',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '36',
			'lugar' 	=> '48',
			'empresa' 	=> 'Empresa 37',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '37',
			'lugar' 	=> '49',
			'empresa' 	=> 'Empresa 38',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '38',
			'lugar' 	=> '50',
			'empresa' 	=> 'Empresa 39',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '39',
			'lugar' 	=> '51',
			'empresa' 	=> 'Empresa 40',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '40',
			'lugar' 	=> '52',
			'empresa' 	=> 'Empresa 41',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '41',
			'lugar' 	=> '53',
			'empresa' 	=> 'Empresa 42',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '42',
			'lugar' 	=> '54',
			'empresa' 	=> 'Empresa 43',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '43',
			'lugar' 	=> '55',
			'empresa' 	=> 'Empresa 44',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '44',
			'lugar' 	=> '56',
			'empresa' 	=> 'Empresa 45',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '45',
			'lugar' 	=> '57',
			'empresa' 	=> 'Empresa 46',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '46',
			'lugar' 	=> '58',
			'empresa' 	=> 'Empresa 47',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '47',
			'lugar' 	=> '59',
			'empresa' 	=> 'Empresa 48',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '48',
			'lugar' 	=> '60',
			'empresa' 	=> 'Empresa 49',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '49',
			'lugar' 	=> '61',
			'empresa' 	=> 'Empresa 50',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '50',
			'lugar' 	=> '62',
			'empresa' 	=> 'Empresa 51',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '51',
			'lugar' 	=> '63',
			'empresa' 	=> 'Empresa 52',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '52',
			'lugar' 	=> '64',
			'empresa' 	=> 'Empresa 53',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '53',
			'lugar' 	=> '65',
			'empresa' 	=> 'Empresa 54',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '54',
			'lugar' 	=> '66',
			'empresa' 	=> 'Empresa 55',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '55',
			'lugar' 	=> '67',
			'empresa' 	=> 'Empresa 56',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '56',
			'lugar' 	=> '68',
			'empresa' 	=> 'Empresa 57',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '57',
			'lugar' 	=> '69',
			'empresa' 	=> 'Empresa 58',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '58',
			'lugar' 	=> '70',
			'empresa' 	=> 'Empresa 59',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '59',
			'lugar' 	=> '71',
			'empresa' 	=> 'Empresa 60',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '60',
			'lugar' 	=> '72',
			'empresa' 	=> 'Empresa 61',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '61',
			'lugar' 	=> '73',
			'empresa' 	=> 'Empresa 62',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '62',
			'lugar' 	=> '74',
			'empresa' 	=> 'Empresa 63',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '63',
			'lugar' 	=> '75',
			'empresa' 	=> 'Empresa 64',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '64',
			'lugar' 	=> '76',
			'empresa' 	=> 'Empresa 65',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '65',
			'lugar' 	=> '77',
			'empresa' 	=> 'Empresa 66',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '66',
			'lugar' 	=> '78',
			'empresa' 	=> 'Empresa 67',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '67',
			'lugar' 	=> '79',
			'empresa' 	=> 'Empresa 68',
			'estatus' 	=> $disponible,
		],
	];

	$planos2 = [
		[
			'idx' 		=> '0',
			'lugar' 	=> '1',
			'empresa' 	=> 'Empresa 1',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '1',
			'lugar' 	=> '2',
			'empresa' 	=> 'Empresa 2',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '2',
			'lugar' 	=> '3',
			'empresa' 	=> 'Empresa 3',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '3',
			'lugar' 	=> '4',
			'empresa' 	=> 'Empresa 4',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '4',
			'lugar' 	=> '5',
			'empresa' 	=> 'Empresa 5',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '5',
			'lugar' 	=> '6',
			'empresa' 	=> 'Empresa 6',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '6',
			'lugar' 	=> '7',
			'empresa' 	=> 'Empresa 7',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '7',
			'lugar' 	=> '8',
			'empresa' 	=> 'Empresa 8',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '8',
			'lugar' 	=> '9',
			'empresa' 	=> 'Empresa 9',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '9',
			'lugar' 	=> '10',
			'empresa' 	=> 'Empresa 10',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '10',
			'lugar' 	=> '11',
			'empresa' 	=> 'Empresa 11',
			'estatus' 	=> $disponible,
		],
	];

	$planos3 = [
		[
			'idx' 		=> '0',
			'lugar' 	=> '1',
			'empresa' 	=> 'Empresa 1',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '1',
			'lugar' 	=> '2',
			'empresa' 	=> 'Empresa 2',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '2',
			'lugar' 	=> '3',
			'empresa' 	=> 'Empresa 3',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '3',
			'lugar' 	=> '4',
			'empresa' 	=> 'Empresa 4',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '4',
			'lugar' 	=> '5',
			'empresa' 	=> 'Empresa 5',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '5',
			'lugar' 	=> '6',
			'empresa' 	=> 'Empresa 6',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '6',
			'lugar' 	=> '7',
			'empresa' 	=> 'Empresa 7',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '7',
			'lugar' 	=> '8',
			'empresa' 	=> 'Empresa 8',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '8',
			'lugar' 	=> '9',
			'empresa' 	=> 'Empresa 9',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '9',
			'lugar' 	=> '10',
			'empresa' 	=> 'Empresa 10',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '10',
			'lugar' 	=> '11',
			'empresa' 	=> 'Empresa 11',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '11',
			'lugar' 	=> '12',
			'empresa' 	=> 'Empresa 12',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '12',
			'lugar' 	=> '13',
			'empresa' 	=> 'Empresa 13',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '13',
			'lugar' 	=> '14',
			'empresa' 	=> 'Empresa 14',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '14',
			'lugar' 	=> '15',
			'empresa' 	=> 'Empresa 15',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '15',
			'lugar' 	=> '16',
			'empresa' 	=> 'Empresa 16',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '16',
			'lugar' 	=> '17',
			'empresa' 	=> 'Empresa 17',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '17',
			'lugar' 	=> '18',
			'empresa' 	=> 'Empresa 18',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '18',
			'lugar' 	=> '19',
			'empresa' 	=> 'Empresa 19',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '19',
			'lugar' 	=> '20',
			'empresa' 	=> 'Empresa 20',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '20',
			'lugar' 	=> '21',
			'empresa' 	=> 'Empresa 21',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '21',
			'lugar' 	=> '22',
			'empresa' 	=> 'Empresa 22',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '22',
			'lugar' 	=> '23',
			'empresa' 	=> 'Empresa 23',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '23',
			'lugar' 	=> '24',
			'empresa' 	=> 'Empresa 24',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '24',
			'lugar' 	=> '25',
			'empresa' 	=> 'Empresa 25',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '25',
			'lugar' 	=> '26',
			'empresa' 	=> 'Empresa 26',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '26',
			'lugar' 	=> '27',
			'empresa' 	=> 'Empresa 27',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '27',
			'lugar' 	=> '28',
			'empresa' 	=> 'Empresa 28',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '28',
			'lugar' 	=> '29',
			'empresa' 	=> 'Empresa 29',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '29',
			'lugar' 	=> '30',
			'empresa' 	=> 'Empresa 30',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '30',
			'lugar' 	=> '31',
			'empresa' 	=> 'Empresa 31',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '31',
			'lugar' 	=> '32',
			'empresa' 	=> 'Empresa 32',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '32',
			'lugar' 	=> '33',
			'empresa' 	=> 'Empresa 33',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '33',
			'lugar' 	=> '34',
			'empresa' 	=> 'Empresa 34',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '34',
			'lugar' 	=> '35',
			'empresa' 	=> 'Empresa 35',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '35',
			'lugar' 	=> '36',
			'empresa' 	=> 'Empresa 36',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '36',
			'lugar' 	=> '37',
			'empresa' 	=> 'Empresa 37',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '37',
			'lugar' 	=> '38',
			'empresa' 	=> 'Empresa 38',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '38',
			'lugar' 	=> '39',
			'empresa' 	=> 'Empresa 39',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '39',
			'lugar' 	=> '40',
			'empresa' 	=> 'Empresa 40',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '40',
			'lugar' 	=> '41',
			'empresa' 	=> 'Empresa 41',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '41',
			'lugar' 	=> '42',
			'empresa' 	=> 'Empresa 42',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '42',
			'lugar' 	=> '43',
			'empresa' 	=> 'Empresa 43',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '43',
			'lugar' 	=> '44',
			'empresa' 	=> 'Empresa 44',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '44',
			'lugar' 	=> '45',
			'empresa' 	=> 'Empresa 45',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '45',
			'lugar' 	=> '46',
			'empresa' 	=> 'Empresa 46',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '46',
			'lugar' 	=> '47',
			'empresa' 	=> 'Empresa 47',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '47',
			'lugar' 	=> '48',
			'empresa' 	=> 'Empresa 48',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '48',
			'lugar' 	=> '49',
			'empresa' 	=> 'Empresa 49',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '49',
			'lugar' 	=> '50',
			'empresa' 	=> 'Empresa 50',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '50',
			'lugar' 	=> '51',
			'empresa' 	=> 'Empresa 51',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '51',
			'lugar' 	=> '52',
			'empresa' 	=> 'Empresa 52',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '52',
			'lugar' 	=> '53',
			'empresa' 	=> 'Empresa 53',
			'estatus' 	=> $disponible,
		],
		[
			'idx' 		=> '53',
			'lugar' 	=> '54',
			'empresa' 	=> 'Empresa 54',
			'estatus' 	=> $disponible,
		],
	];
?>